name: Build and Test
on: [pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.12, 1.13]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v1
      - name: Build
        env:
          GO111MODULE: "on"
        run: for i in $(ls -1 cmd); do (cd cmd/$i && go build); done
      - name: Vet
        env:
          GO111MODULE: "on"
        run: for i in $(ls -1 cmd); do (cd cmd/$i && go vet); done
